package com.codgo.ulock.audit;

public enum AuditAction {
    LOGIN_SUCCEEDED,
    LOGIN_FAILED,
    ACCOUNT_LOCKED,
    LOGOUT,
    REFRESH_TOKEN_REUSED,
    TENANT_ACCESS_DENIED,
    TENANT_CREATED,
    TENANT_UPDATED,
    USER_CREATED,
    USER_UPDATED,
    USER_PASSWORD_RESET,
    ROLE_CREATED,
    ROLE_UPDATED,
    ROLE_DELETED,
    ROLE_PERMISSIONS_REPLACED,
    ROLE_ASSIGNED,
    ROLE_REVOKED,
    PERMISSION_CREATED,
    MACHINE_CLIENT_CREATED,
    MACHINE_CLIENT_UPDATED
}
